version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-ai_bot_db}
      MARIADB_USER: ${MARIADB_USER:-ai_bot}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    ports:
      - "127.0.0.1:${MARIADB_PORT:-3306}:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 b/bot.py
    restart: always
    depends_on:
      - mariadb
    environment:
      - DATABASE_URL=mysql+aiomysql://${MARIADB_USER:-ai_bot}:${MARIADB_PASSWORD:-password}@mariadb:3306/${MARIADB_DATABASE:-ai_bot_db}
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
